#!/usr/bin/env bash
#Bash script that will display information about subdomains
if [ "$2" ]
then
    dig "$2.$1" | awk -v SUB="$2" '/ANSWER SECTION:/ { getline; FS="\t"; print "The subdomain", SUB, "is a", $4, "record and points to", $5; }'
else
    dig "www.$1" | awk '/ANSWER SECTION:/ { getline; FS="\t"; print "The subdomain www is a", $4, "record and points to", $5; }'
        dig "lb-01.$1" | awk '/ANSWER SECTION:/ { getline; FS="\t"; print "The subdomain lb-01 is a", $4, "record and points to", $5; }'
        dig "web-01.$1" | awk '/ANSWER SECTION:/ { getline; FS="\t"; print "The subdomain web-01 is a", $4, "record and points to", $5; }'
        dig "web-02.$1" | awk '/ANSWER SECTION:/ { getline; FS="\t"; print "The subdomain web-02 is a", $4, "record and points to", $5; }'
fi
