#!/usr/bin/env bash
#configure a server with Nginx
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo chmod '0777' /var/www/html/index.html
echo "Holberton School" > /var/www/html/index.html
sudo service nginx start
