#!/usr/bin/env bash
#configure a server with Nginx
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Holberton School" > /var/www/html/index.html
redirect="\n\t/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n\t"
sudo sed -i "$redirect" /etc/nginx/sites-available/default
sudo service nginx restart
