#!/usr/bin/env bash
#Configure your Nginx server to have a custom 404 page
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Holberton School" > /var/www/html/index.html
REDIRECT="/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "$REDIRECT" /etc/nginx/sites-available/default
sudo touch /usr/share/nginx/html/404error.html
sudo chmod '0777' /usr/share/nginx/html/404error.html
echo -e "Ceci n'est pas une page\n" > /usr/share/nginx/html/404error.html
error_page="/listen 80 default_server/a error_page 404 /404error.html;"
sudo sed -i "$error_page" /etc/nginx/sites-available/default
sudo service nginx restart
